oidcdata:
    container_name: oidc-data
    image: learninglayers/openidconnect-data#0.0.1
    env_file:
        - common.env
        - services/openidconnect/openidconnect.env
oidc:
    container_name: adapter
    image: learninglayers/openidconnect#0.0.1
    env_file:
        - common.env
        - services/openidconnect/openidconnect.env
    volumes_from:
        - oidcdata
    links:
        - mysql
        - openldap
    volumes:
        - /dev/urandom:/dev/random
